"""Add class new fields

Revision ID: 1ec5fe6feabc
Revises: 7f1d9a2b8c4b
Create Date: 2026-01-01 10:35:14.057461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ec5fe6feabc'
down_revision = '7f1d9a2b8c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first to avoid errors with existing data
    op.add_column('Class', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.add_column('Class', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('Class', sa.Column('class_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('Class', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    # For owner_user_id, try to get from created_by username
    # For now, we'll just set a default UUID or update manually
    op.execute("""
        UPDATE "Class" 
        SET 
            is_public = false,
            updated_at = created_at
        WHERE is_public IS NULL
    """)
    
    # Try to set owner_user_id from created_by username
    op.execute("""
        UPDATE "Class" c
        SET owner_user_id = u.user_id
        FROM "User" u
        WHERE c.created_by = u.username
        AND c.owner_user_id IS NULL
    """)
    
    # Make columns non-nullable after setting defaults
    op.alter_column('Class', 'owner_user_id', nullable=False)
    op.alter_column('Class', 'is_public', nullable=False)
    op.alter_column('Class', 'updated_at', nullable=False)
    
    op.create_index(op.f('ix_Class_class_code'), 'Class', ['class_code'], unique=True)
    op.create_foreign_key(None, 'Class', 'User', ['owner_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Class', type_='foreignkey')
    op.drop_index(op.f('ix_Class_class_code'), table_name='Class')
    op.drop_column('Class', 'updated_at')
    op.drop_column('Class', 'class_code')
    op.drop_column('Class', 'is_public')
    op.drop_column('Class', 'owner_user_id')
    # ### end Alembic commands ###
