"""Add cascade delete to ClassMember

Revision ID: 3d491e651c3d
Revises: 1ec5fe6feabc
Create Date: 2026-01-01 11:59:17.855120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3d491e651c3d'
down_revision = '1ec5fe6feabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key constraint
    op.drop_constraint('ClassMember_class_id_fkey', 'ClassMember', type_='foreignkey')
    
    # Recreate with CASCADE delete
    op.create_foreign_key(
        'ClassMember_class_id_fkey',
        'ClassMember', 'Class',
        ['class_id'], ['class_id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CASCADE constraint
    op.drop_constraint('ClassMember_class_id_fkey', 'ClassMember', type_='foreignkey')
    
    # Recreate without CASCADE
    op.create_foreign_key(
        'ClassMember_class_id_fkey',
        'ClassMember', 'Class',
        ['class_id'], ['class_id']
    )
    # ### end Alembic commands ###
