"""remove Quizz model

Revision ID: 5c76c5bc26b5
Revises: 903bb114ce1d
Create Date: 2025-12-05 08:13:12.866857

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c76c5bc26b5'
down_revision = '903bb114ce1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attribute',
    sa.Column('attribute_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_trans', sa.Text(), nullable=True),
    sa.Column('content_type', postgresql.ENUM('DEFAULT', 'AI_GENERATED', name='contenttype', create_type=False), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.drop_table('Quizz')
    op.drop_table('Paragraph')
    op.add_column('Term', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('Term', sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('Term', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('Term', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Term', 'attributes')
    op.drop_column('Term', 'image_url')
    op.drop_column('Term', 'subcategory')
    op.drop_column('Term', 'category')
    op.create_table('Paragraph',
    sa.Column('paragraph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('studyset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_trans', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_type', postgresql.ENUM('DEFAULT', 'AI_GENERATED', name='contenttype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], name=op.f('Paragraph_studyset_id_fkey')),
    sa.PrimaryKeyConstraint('paragraph_id', name=op.f('Paragraph_pkey'))
    )
    op.create_table('Quizz',
    sa.Column('quizz_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('studyset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_type', postgresql.ENUM('DEFAULT', 'AI_GENERATED', name='contenttype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], name=op.f('Quizz_studyset_id_fkey')),
    sa.PrimaryKeyConstraint('quizz_id', name=op.f('Quizz_pkey'))
    )
    op.drop_table('Attribute')
    # ### end Alembic commands ###
