"""add_repetitions_field_to_study_activity

Revision ID: 5e24daafd151
Revises: 301ee1a30633
Create Date: 2026-01-09 12:32:06.222167

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5e24daafd151'
down_revision = '301ee1a30633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='Category')
    op.drop_index(op.f('ix_category_owner_id'), table_name='Category')
    op.create_index(op.f('ix_Category_name'), 'Category', ['name'], unique=False)
    op.create_index(op.f('ix_Category_owner_id'), 'Category', ['owner_id'], unique=False)
    op.add_column('StudyActivity', sa.Column('repetitions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudyActivity', 'repetitions')
    op.drop_index(op.f('ix_Category_owner_id'), table_name='Category')
    op.drop_index(op.f('ix_Category_name'), table_name='Category')
    op.create_index(op.f('ix_category_owner_id'), 'Category', ['owner_id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'Category', ['name'], unique=False)
    # ### end Alembic commands ###
