"""remove_is_correct_field_from_study_activity

Revision ID: 7f00dc22597d
Revises: 5e24daafd151
Create Date: 2026-01-09 12:52:31.794743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f00dc22597d'
down_revision = '5e24daafd151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StudyActivity', 'is_correct')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudyActivity', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
