"""Add membership status and approval system

Revision ID: 7f107a160832
Revises: 3d491e651c3d
Create Date: 2026-01-01 12:20:42.928491

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f107a160832'
down_revision = '3d491e651c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    op.execute("CREATE TYPE membershipstatus AS ENUM ('ACTIVE', 'PENDING', 'INVITED', 'REJECTED', 'LEFT')")
    
    # Add columns as nullable first
    op.add_column('ClassMember', sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'INVITED', 'REJECTED', 'LEFT', name='membershipstatus'), nullable=True))
    op.add_column('ClassMember', sa.Column('invited_by', sa.Uuid(), nullable=True))
    op.add_column('ClassMember', sa.Column('approved_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE \"ClassMember\" SET status = 'ACTIVE' WHERE status IS NULL")
    op.execute("UPDATE \"ClassMember\" SET approved_at = joined_at WHERE approved_at IS NULL")
    
    # Make status non-nullable
    op.alter_column('ClassMember', 'status', nullable=False)
    
    # Update foreign keys
    op.drop_constraint('ClassMember_class_id_fkey', 'ClassMember', type_='foreignkey')
    op.create_foreign_key(None, 'ClassMember', 'Class', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ClassMember', 'User', ['invited_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClassMember', type_='foreignkey')
    op.drop_constraint(None, 'ClassMember', type_='foreignkey')
    op.create_foreign_key('ClassMember_class_id_fkey', 'ClassMember', 'Class', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_column('ClassMember', 'approved_at')
    op.drop_column('ClassMember', 'invited_by')
    op.drop_column('ClassMember', 'status')
    op.execute('DROP TYPE membershipstatus')
    # ### end Alembic commands ###
