"""add_test_system_with_questions_and_reattempts

Revision ID: 8770d1e4cc30
Revises: 0c22457276fe
Create Date: 2026-01-04 03:34:20.979739

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8770d1e4cc30'
down_revision = '0c22457276fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestAttempt',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['Test.test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('TestQuestion',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'ESSAY', name='questiontype'), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['Term.term_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['Test.test_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('ReattemptRequest',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reattemptstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['TestAttempt.attempt_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('TestAnswer',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['TestAttempt.attempt_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['TestQuestion.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.drop_table('TestResult')
    op.add_column('Test', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('Test', sa.Column('show_answers', sa.Boolean(), nullable=False))
    op.add_column('Test', sa.Column('question_types', sa.JSON(), nullable=True))
    op.add_column('Test', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.add_column('Test', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'Test', 'User', ['created_by'], ['user_id'])
    op.drop_column('Test', 'test_types')
    op.drop_column('Test', 'content_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('content_type', postgresql.ENUM('DEFAULT', 'AI_GENERATED', name='contenttype'), autoincrement=False, nullable=False))
    op.add_column('Test', sa.Column('test_types', postgresql.ENUM('MULTIPLE_CHOICE', 'WRITTEN', 'MIXED', name='testtype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Test', type_='foreignkey')
    op.drop_column('Test', 'updated_at')
    op.drop_column('Test', 'created_by')
    op.drop_column('Test', 'question_types')
    op.drop_column('Test', 'show_answers')
    op.drop_column('Test', 'description')
    op.create_table('TestResult',
    sa.Column('test_result_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['Test.test_id'], name=op.f('TestResult_test_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name=op.f('TestResult_user_id_fkey')),
    sa.PrimaryKeyConstraint('test_result_id', name=op.f('TestResult_pkey'))
    )
    op.drop_table('TestAnswer')
    op.drop_table('ReattemptRequest')
    op.drop_table('TestQuestion')
    op.drop_table('TestAttempt')
    # ### end Alembic commands ###
