"""add_chat_conversation_models

Revision ID: 90fdd5195bd6
Revises: a5514c0fb815
Create Date: 2026-01-04 20:26:57.754351

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90fdd5195bd6'
down_revision = 'a5514c0fb815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatConversation',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('INITIAL', 'WAITING_INTENT', 'COLLECTING_TEST_PARAMS', 'GENERATING', 'COMPLETED', name='conversationstate'), nullable=False),
    sa.Column('intent', sa.Enum('GEN_TEST', 'GEN_PARAGRAPH', 'ASK_QUESTION', 'COLLECT_PARAMS', name='conversationintent'), nullable=True),
    sa.Column('collected_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('ChatMessage',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ChatConversation.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_column('Term', 'category')
    op.drop_column('Term', 'subcategory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Term', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('Term', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_table('ChatMessage')
    op.drop_table('ChatConversation')
    # ### end Alembic commands ###
