"""change_image_url_to_text

Revision ID: a5514c0fb815
Revises: ea99bae7785f
Create Date: 2026-01-04 19:40:05.419897

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5514c0fb815'
down_revision = 'ea99bae7785f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change image_url from VARCHAR(1024) to TEXT to support base64 images
    op.alter_column('Term', 'image_url',
                    existing_type=sa.String(length=1024),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to VARCHAR(1024)
    op.alter_column('Term', 'image_url',
                    existing_type=sa.Text(),
                    type_=sa.String(length=1024),
                    existing_nullable=True)
    # ### end Alembic commands ###
