"""add_time_limit_to_test

Revision ID: bab5b45e2275
Revises: 8770d1e4cc30
Create Date: 2026-01-04 09:19:08.899453

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bab5b45e2275'
down_revision = '8770d1e4cc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Test', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Test', 'time_limit')
    # ### end Alembic commands ###
