"""add_class_studyset_table

Revision ID: bc20d7fe1292
Revises: 7f107a160832
Create Date: 2026-01-02 06:48:40.743653

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc20d7fe1292'
down_revision = '7f107a160832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClassStudySet',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], ),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('class_id', 'studyset_id')
    )
    op.create_index('ix_classstudyset_class_studyset', 'ClassStudySet', ['class_id', 'studyset_id'], unique=False)
    op.drop_constraint(op.f('ClassMember_class_id_fkey'), 'ClassMember', type_='foreignkey')
    op.create_foreign_key(None, 'ClassMember', 'Class', ['class_id'], ['class_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClassMember', type_='foreignkey')
    op.create_foreign_key(op.f('ClassMember_class_id_fkey'), 'ClassMember', 'Class', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_index('ix_classstudyset_class_studyset', table_name='ClassStudySet')
    op.drop_table('ClassStudySet')
    # ### end Alembic commands ###
