"""move_category_from_term_to_studyset

Revision ID: ea99bae7785f
Revises: bab5b45e2275
Create Date: 2026-01-04 18:54:35.040532

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea99bae7785f'
down_revision = 'bab5b45e2275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add category and subcategory columns to StudySet table
    op.add_column('StudySet', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('StudySet', sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before dropping to avoid errors
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' 
        AND table_name = 'StudySet'
        AND column_name IN ('category', 'subcategory')
    """))
    existing_columns = [row[0] for row in result]
    
    if 'subcategory' in existing_columns:
        op.drop_column('StudySet', 'subcategory')
    if 'category' in existing_columns:
        op.drop_column('StudySet', 'category')
    # ### end Alembic commands ###
