"""Initialize new database schema

Revision ID: ee3cbed59841
Revises: 
Create Date: 2025-11-12 14:36:18.021395

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee3cbed59841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Class',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone_numbers', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('ClassMember',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', 'CO_TEACHER', name='classrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('class_id', 'user_id')
    )
    op.create_index('ix_classmember_user_class', 'ClassMember', ['user_id', 'class_id'], unique=False)
    op.create_table('StudySet',
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Enum('DEFAULT', 'AI_GENERATED', name='contenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('studyset_id')
    )
    op.create_table('AIGeneratedContents',
    sa.Column('ai_content_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('generate_type', sa.Enum('QUIZZ', 'TEST', 'PARAGRAPH', name='generatetype'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('ai_content_id')
    )
    op.create_table('Paragraph',
    sa.Column('paragraph_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_trans', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('DEFAULT', 'AI_GENERATED', name='contenttype'), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('paragraph_id')
    )
    op.create_table('ProgressSummary',
    sa.Column('progress_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mastered_terms', sa.Integer(), nullable=False),
    sa.Column('reviewing_terms', sa.Integer(), nullable=False),
    sa.Column('forgotten_terms', sa.Integer(), nullable=False),
    sa.Column('average_recall_score', sa.Float(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_table('Quizz',
    sa.Column('quizz_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Enum('DEFAULT', 'AI_GENERATED', name='contenttype'), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('quizz_id')
    )
    op.create_table('Term',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('term_text', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_table('Test',
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('test_types', sa.Enum('MULTIPLE_CHOICE', 'WRITTEN', 'MIXED', name='testtype'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('DEFAULT', 'AI_GENERATED', name='contenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('StudyActivity',
    sa.Column('activity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('studyset_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('recall_score', sa.Integer(), nullable=False),
    sa.Column('ef', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studyset_id'], ['StudySet.studyset_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['Term.term_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('TestResult',
    sa.Column('test_result_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['Test.test_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('test_result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TestResult')
    op.drop_table('StudyActivity')
    op.drop_table('Test')
    op.drop_table('Term')
    op.drop_table('Quizz')
    op.drop_table('ProgressSummary')
    op.drop_table('Paragraph')
    op.drop_table('AIGeneratedContents')
    op.drop_table('StudySet')
    op.drop_index('ix_classmember_user_class', table_name='ClassMember')
    op.drop_table('ClassMember')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_table('Class')
    # ### end Alembic commands ###
